sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7.7'
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i -g npm@^4.3.0
  - npm i -g typings
before_script:
  - npm prune
script:
  - npm run build:travis
after_success:
  - npm publish
branches:
  only:
    - master
env:
  global:
    - secure: j51BRoI+ZCVzSOstSY2z8GLQMIPWQgJTwaPmx/725Trp16hmyMetvjeE+7m1buU7D85D+iYC2fd0wCqUClAZIJrdbvcgiR9AeAHG/yJu/Jv1hQIW8N6pgRELoz0c5WjxhMYQDOkcOCqf5w3Udc9jXI3VKY8g/EW+seEYx/m5rgcfEIhWPEuCYhuECCj4DVD3+9PlOSvFjdd+02ebMI8CqmdGWFs4giISY07117NSk6HJK232ZMDT0XoQey+jovMgoxXEgenGAkA6R12jfTyR4uWLbkUv70/pPcf+E6lfjSlRlW9KFHAGvIRvqPo2wZeIHi1VYZ3PgI/w0RHyUf/E9y3RygqZrpVYualLUbk8wNrgjHNuxxHCoPFY7ErZOpR0Ez2lc9rA0yPyP97fg5HD4SdYImWAsIgZbXMMqsnNeqmdzJHcnXhhDpzGXVE+xrLNMKb8uA0R0VBf9PGyrWTkreuDDysbFguSPPJP8PbVj1KY0GIrL8mtlCzgA7KylMLw8cTibKiz5tgQ/rMMaqMLX5XME+hdmW1A4niyPTBTxL5vEU+gb5n0w4yiyOamlvBXHCmQJCUcTOFswcJti0j7L0Mu7dK5XxGaqlxv2WQ4zBPwIkggMR+Se4Ce5ccOetS5uJDdN63/884KceHvYFnnIF6/0GYVKqAqUyuFCsYrG2A=