sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7.7'
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i -g npm@latest
  - npm i -g typings
before_script:
  - npm prune
script:
  - npm run build:travis
after_success:
  - npm run semantic-release
branches:
  only:
    - master